version: '3.7'
services:
  rabbitmq:
    container_name: test-rabbit-node
    image: rabbitmq:3-management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
      - '8080:8080'
